import type { Lang } from '../data/site';

export type Tool = {
  id: string;
  slug: string;
  type: 'built-in' | 'redirect';
  status: 'live' | 'coming-soon';
  categorySlug: string;
  fa: { title: string; shortDescription: string; longDescription: string; seoTitle: string; seoDescription: string; howTo: string[]; faq: { q: string; a: string }[] };
  en: { title: string; shortDescription: string; longDescription: string; seoTitle: string; seoDescription: string; howTo: string[]; faq: { q: string; a: string }[] };
  tags: string[];
  searchTerms: string[];
  featured: boolean;
  sponsored: boolean;
  showExternalBadge: boolean;
  relatedToolSlugs: string[];
  outboundUrl?: string;
  updatedAt: string;
};

export const tools: Tool[] = [
  { id: '1', slug: 'image-compressor', type: 'built-in', status: 'live', categorySlug: 'image-tools', fa: { title: 'کاهش حجم عکس', shortDescription: 'کاهش حجم عکس در مرورگر.', longDescription: 'بدون ارسال فایل، کیفیت و حجم را کنترل کنید.', seoTitle: 'کاهش حجم عکس آنلاین | بل بوره', seoDescription: 'کاهش حجم عکس رایگان و سریع در مرورگر.', howTo: ['عکس را انتخاب کنید', 'کیفیت را تنظیم کنید', 'دانلود کنید'], faq: [{ q: 'آیا فایل آپلود می شود؟', a: 'خیر، همه چیز در مرورگر انجام می شود.' }] }, en: { title: 'Image Compressor', shortDescription: 'Compress images in browser.', longDescription: 'Control quality and file size without upload.', seoTitle: 'Online Image Compressor | Belboore', seoDescription: 'Free browser-based image compressor.', howTo: ['Choose image', 'Set quality', 'Download'], faq: [{ q: 'Are files uploaded?', a: 'No, processing happens in your browser.' }] }, tags: ['image', 'compress'], searchTerms: ['compress image', 'کاهش حجم عکس'], featured: true, sponsored: false, showExternalBadge: false, relatedToolSlugs: ['image-converter', 'image-resizer'], updatedAt: '2026-05-29' },
  { id: '2', slug: 'image-converter', type: 'built-in', status: 'live', categorySlug: 'image-tools', fa: { title: 'تبدیل فرمت عکس', shortDescription: 'تبدیل JPG, PNG, WebP.', longDescription: 'تبدیل سریع فرمت تصویر در سمت کاربر.', seoTitle: 'تبدیل عکس آنلاین | بل بوره', seoDescription: 'تبدیل فرمت عکس بدون آپلود فایل.', howTo: ['عکس را انتخاب کنید', 'فرمت خروجی را بزنید', 'دانلود کنید'], faq: [{ q: 'چه فرمتی پشتیبانی می شود؟', a: 'JPG, PNG, WebP' }] }, en: { title: 'Image Converter', shortDescription: 'Convert JPG, PNG, WebP.', longDescription: 'Fast client-side image format conversion.', seoTitle: 'Online Image Converter | Belboore', seoDescription: 'Convert image formats without upload.', howTo: ['Choose image', 'Pick output format', 'Download'], faq: [{ q: 'Which formats are supported?', a: 'JPG, PNG, WebP' }] }, tags: ['image', 'convert'], searchTerms: ['image converter', 'تبدیل عکس'], featured: true, sponsored: false, showExternalBadge: false, relatedToolSlugs: ['image-compressor', 'image-resizer'], updatedAt: '2026-05-29' },
  { id: '3', slug: 'image-resizer', type: 'built-in', status: 'live', categorySlug: 'image-tools', fa: { title: 'تغییر اندازه عکس', shortDescription: 'تغییر عرض و ارتفاع.', longDescription: 'برای شبکه های اجتماعی یا وب، اندازه دقیق بسازید.', seoTitle: 'تغییر اندازه عکس آنلاین | بل بوره', seoDescription: 'ریسایز تصویر سریع و رایگان.', howTo: ['عکس را انتخاب کنید', 'اندازه را وارد کنید', 'دانلود کنید'], faq: [{ q: 'نسبت تصویر حفظ می شود؟', a: 'در حالت پیش فرض بله.' }] }, en: { title: 'Image Resizer', shortDescription: 'Resize width and height.', longDescription: 'Create exact dimensions for web and social media.', seoTitle: 'Online Image Resizer | Belboore', seoDescription: 'Fast and free image resizing.', howTo: ['Choose image', 'Set dimensions', 'Download'], faq: [{ q: 'Aspect ratio preserved?', a: 'Yes by default.' }] }, tags: ['image', 'resize'], searchTerms: ['resize image', 'تغییر اندازه عکس'], featured: true, sponsored: false, showExternalBadge: false, relatedToolSlugs: ['image-compressor'], updatedAt: '2026-05-29' },
  { id: '4', slug: 'text-case-converter', type: 'built-in', status: 'live', categorySlug: 'text-tools', fa: { title: 'تبدیل حالت متن', shortDescription: 'حروف کوچک، بزرگ، عنوان.', longDescription: 'متن را به حالت های مختلف نوشتاری تبدیل کنید.', seoTitle: 'تبدیل حالت متن | بل بوره', seoDescription: 'ابزار رایگان تبدیل حروف متن.', howTo: ['متن را وارد کنید', 'نوع تبدیل را انتخاب کنید', 'کپی کنید'], faq: [{ q: 'برای فارسی هم کار می کند؟', a: 'بله، برخی حالت ها به انگلیسی اختصاصی است.' }] }, en: { title: 'Text Case Converter', shortDescription: 'Upper, lower, title case.', longDescription: 'Convert text casing styles instantly.', seoTitle: 'Text Case Converter | Belboore', seoDescription: 'Free text casing converter.', howTo: ['Paste text', 'Pick case', 'Copy output'], faq: [{ q: 'Does it work with Persian?', a: 'Yes, but some modes are English-specific.' }] }, tags: ['text', 'case'], searchTerms: ['case converter', 'تبدیل حروف'], featured: true, sponsored: false, showExternalBadge: false, relatedToolSlugs: ['json-formatter-validator'], updatedAt: '2026-05-29' },
  { id: '5', slug: 'json-formatter-validator', type: 'built-in', status: 'live', categorySlug: 'dev-tools', fa: { title: 'فرمت و اعتبارسنج JSON', shortDescription: 'زیبا سازی و بررسی JSON.', longDescription: 'JSON را فرمت کنید و خطای ساختار را ببینید.', seoTitle: 'فرمت JSON آنلاین | بل بوره', seoDescription: 'JSON Formatter و Validator رایگان.', howTo: ['JSON را وارد کنید', 'فرمت را بزنید', 'نتیجه را کپی کنید'], faq: [{ q: 'خطاها نمایش داده می شوند؟', a: 'بله، خطای دقیق نشان داده می شود.' }] }, en: { title: 'JSON Formatter & Validator', shortDescription: 'Beautify and validate JSON.', longDescription: 'Format JSON and catch parse errors instantly.', seoTitle: 'JSON Formatter Online | Belboore', seoDescription: 'Free JSON formatter and validator.', howTo: ['Paste JSON', 'Click format', 'Copy output'], faq: [{ q: 'Do errors show?', a: 'Yes, parse errors are displayed.' }] }, tags: ['json', 'dev'], searchTerms: ['json formatter', 'فرمت json'], featured: true, sponsored: false, showExternalBadge: false, relatedToolSlugs: ['text-case-converter'], updatedAt: '2026-05-29' },
  { id: '6', slug: 'cach', type: 'redirect', status: 'live', categorySlug: 'productivity-tools', fa: { title: 'Cach', shortDescription: 'چت و تماس امن', longDescription: 'برای ایجاد ارتباطی امن و آسان.', seoTitle: 'Cach در بل بوره', seoDescription: 'معرفی ابزار Cach و لینک مستقیم.', howTo: ['معرفی را بخوانید', 'به سایت رسمی بروید'], faq: [{ q: 'آیا این ابزار داخلی است؟', a: 'خیر، ابزار خارجی انتخابی است.' }] }, en: { title: 'Cach', shortDescription: 'Quick notes and work organization.', longDescription: 'Useful for daily task notes and planning.', seoTitle: 'Cach on Belboore', seoDescription: 'Cach overview with direct outbound link.', howTo: ['Read overview', 'Open official website'], faq: [{ q: 'Is this built-in?', a: 'No, this is a curated external tool.' }] }, tags: ['productivity'], searchTerms: ['cach'], featured: true, sponsored: false, showExternalBadge: true, relatedToolSlugs: ['haamcall'], outboundUrl: 'https://cach.ir', updatedAt: '2026-05-29' },
  { id: '7', slug: 'haamcall', type: 'redirect', status: 'live', categorySlug: 'productivity-tools', fa: { title: 'Haamcall', shortDescription: 'برگزاری تماس و جلسات سریع.', longDescription: 'ابزار ارتباطی برای جلسات تیمی.', seoTitle: 'Haamcall در بل بوره', seoDescription: 'معرفی Haamcall با لینک مستقیم.', howTo: ['ویژگی ها را ببینید', 'در سایت ابزار ادامه دهید'], faq: [{ q: 'لینک خارجی است؟', a: 'بله، در تب جدید باز می شود.' }] }, en: { title: 'Haamcall', shortDescription: 'Fast calls and meeting collaboration.', longDescription: 'Communication tool for team meetings.', seoTitle: 'Haamcall on Belboore', seoDescription: 'Haamcall landing and redirect page.', howTo: ['Review benefits', 'Continue on official site'], faq: [{ q: 'External link?', a: 'Yes, opens in a new tab.' }] }, tags: ['meeting'], searchTerms: ['haamcall'], featured: false, sponsored: false, showExternalBadge: true, relatedToolSlugs: ['cach'], outboundUrl: 'https://haamcall.ir', updatedAt: '2026-05-29' },
  
];

export const getToolBySlug = (slug: string) => tools.find((t) => t.slug === slug);
export const getRelatedTools = (slugs: string[]) => tools.filter((t) => slugs.includes(t.slug));
export const ttext = (tool: Tool, lang: Lang) => (lang === 'fa' ? tool.fa : tool.en);
